### ISSUE TITLE
Odaka pitch visualization is either partly or entirely broken

### ISSUE THREAD

**Issue by Dorako** [WeDontPanic/Jotoba#19] opened 2021-11-22 12:41 UTC
Words like 居間 [2] and 橋 [2] have their pitch accent nucleus on the second mora. Because they are only two mora long, this is classified as odaka, and sounds exactly the same as a heiban [0] word when pronounced in isolation. The difference is whether any attaching particles attach low (in the case of odaka) or high (in the case of heiban). The current pitch contour seen on the 居間 and 橋 pages on jotoba makes them look like heiban words, when they are in fact odaka, which can be verified with another dictionary like this lookup in スーパー大辞林. Kanjium *should* have the neccesary data, so I suspect you're missing a 'drop' class or similar.
<img width="110" alt="image" src="https://user-images.githubusercontent.com/1561190/142863621-e8c46c13-120e-41d1-ab12-e47f29066327.png"> 
<img width="980" alt="image" src="https://user-images.githubusercontent.com/1561190/142863103-368b0e5c-e246-4e4c-a4db-257315aee12f.png">
<img width="980" alt="image" src="https://user-images.githubusercontent.com/1561190/142863148-b59601ef-c637-462f-bd91-02f3ef5c85d6.png">

**Comment by JojiiOfficial** [comment] 2021-11-22 12:46
Duplicate of #15. This issue has been fixed in #11 and will come to Jotoba.de with the new patch

**Closed by JojiiOfficial** 2021-11-22 12:46 UTC
